name: issue-greeter
on:
  issues:
    types: [opened]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: Setting envs
      env:
        REPO: ${{ github.event.repository.name }}
        OWNER: ${{ github.event.repository.owner.login }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
      run: |
        echo "REPO : ${REPO}"
        echo "OWNER: ${OWNER}"
        echo "ISSUE_NUMBER: ${ISSUE_NUMBER}"

    - name: Sleep for a while...
      run:
        sleep 25
