name: issue-greeter
on:
  issues:
    types: [opened]
jobs:
  my-job:
    env:
      REPO: ${{ github.event.repository.name }}
      OWNER: ${{ github.event.repository.owner.login }}
      ISSUE_NUMBER: ${{ github.event.issue.number }}
    runs-on: ubuntu-latest
    steps:
    - name: Setting envs
      #env:
      #  REPO: ${{ github.event.repository.name }}
      #  OWNER: ${{ github.event.repository.owner.login }}
      #  ISSUE_NUMBER: ${{ github.event.issue.number }}
      run: |
        echo "REPO : ${REPO}"
        echo "OWNER: ${OWNER}"
        echo "ISSUE_NUMBER: ${ISSUE_NUMBER}"

    - name: Post back
      #env:
      #  REPO: ${{ github.event.repository.name }}
      #  OWNER: ${{ github.event.repository.owner.login }}
      #  ISSUE_NUMBER: ${{ github.event.issue.number }}
      run: |
        curl -s -X POST https://api.github.com/repos/$OWNER/$REPO/issues/$ISSUE_NUMBER/comments \
          -d '{"body":"Hello ${{ github.event.issue.user.login }}, thanks for your issue!"}' \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"

    - name: Sleep for a while...
      run:
        sleep 5

    - name: Look around
      run: |
        pwd
        ls -la
        echo '=========='
        env
