name: Manual
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: first job, first step
      run: sleep 5
    - name: first job, second step
      run: echo "Hello from the first job!"
    - name: checkout
      uses: actions/checkout@v2
      with:
        path: "gh-act0"
#   - name: first job, third step
#     run: |
#       ip addr show || ifconfig
#       hostname
#       df
    - name: Get Pokemon name
      uses: ./
      id: pokemon
      with:
        pokemon_id: 150
