name: Manual
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: first-job first-step
      run: sleep 5
    - name: first-job second-step
      run: echo "Hello from the first job!"
    - name: first-job third-step
      run: |
        ip addr show || ifconfig
        hostname
        df

  second-job:
    runs-on: ubuntu-latest
    steps:
    - name: second-job first-step
      run: sleep 10
    - name: second-job second-step
      run: echo "Hello from the second job!"
    - name: second-job third-step
      run: |
        ip addr show || ifconfig
        hostname
        df
